### PR TITLE
examples: submitting ideas for example code

### PR DESCRIPTION
**Pull request by johnnohj**
Suggested changes prompted by issues #45   and #46 .

The asyncio_simpletest.py referenced in #45  seemed easily corrected with code from the excellent Cooperative Multitasking tutorial. For #46 , there still is no code posted by the original author almost a year later, so I submit a draft of code, asyncio_event_example.py, I worked up as an exercise for a larger project, and which I hope might be a useful model for anyone else intimidated or stymied by the readthedocs information.

### CODE REVIEW

**Comment by dhalbert** [comment]
Check out using `pre-commit`, which will let you check formmatting issues before you push:
https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code

**Comment by johnnohj** [comment]
> Check out using `pre-commit`

I certainly will - I hope my amateurishness wasn't disruptive.
That said, I think I've done all I can to satisfy the checks. The rest is beyond me. Further help and guidance would be greatly appreciated.

**Comment by dhalbert** [comment]
The remaining fixes look like comment indentation and using double quotes instead of single quotes. If you install pre-commit, it will take care of all this for you. The changes needed will be done automatically when the code is reformatted with `black`. See https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/black. Pre-commit runs `black` for you with the right settings.

**Review by FoamyGuy — APPROVED** [review]
These examples look good to me. 

Thanks for working on this @johnnohj!

**Comment by johnnohj** [comment]
Hey, cool beans! Navigating Git(Hub) as a novice wasn't the most enjoyable part of the process, but worth the bother to give back to the community in some small way. This ought to resolve issue #45 (I think?), and should at least help begin to answer #46 . Thank you, @dhalbert and @FoamyGuy !

Now, back to working on the driver for the VL53L1X sensor :)

**Pull request merged**
